Potential fix for the race condition which cause random tests to fail.
When running tests, we occasionally see intermittent failures like
````
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/tmp/lage-B8VSbk/profile.json'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/lage-B8VSbk/profile.json'
}
````

In ChromeTraceEventsReporter, we open the target file stream in the object constructor and write events with logStream.write(), counting on the nodje cleanup to close file descriptors.

But, in initializeReporters.test.ts, we create a temp folder in `beforeAll` and delete it in `afterAll`.

`write` does not flush buffers, this is done asynchronously by the Node runtime.

Hypothesis: Since we don't wait for buffers to be flushed, we sometimes clean up the temp folder before the last native write, causing an asynchronous error after the "should initialize profile reporter" test has already passed.

This happens out of order, which would explain why "random" tests fail.

ChromeTraceEventsReporterOptions writes data once, in the summary method.
Let's use the Node facility writeFileSync() to do a one-shot write which does not leave a dangling file handle.